project:
  type: website
  output-dir: docs

website:
  title: "medhat-said.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual


