---
title: "Resume"
---

## Experience

Currently, I am a postdoctoral researcher and pharmacometrician at the Princess Máxima Center for Pediatric Oncology (Máxima International) in Utrecht, where I help build and lead an international research programme with partner hospitals across Kenya, Indonesia, Malawi, Egypt, Suriname, and Eurasia.

During my PhD at Amsterdam UMC, I focused on population pharmacokinetic and pharmacodynamic modelling of imatinib, which was studied for its repurposing potential in other disease indications including COVID-19 ARDS and PAH.

Previous modelling experiences include:

-   Development of a novel cardiovascular systems model to quantify drug effects on the inter-relationship between contractility and other hemodynamic variables using pressure-volume loop theory

-   Development of a minimal physiologically based pharmacokinetic (PBPK) model to predict pharmacokinetics and target disposition for recycling and sweeping antibodies

-   Statistical analysis (LASSO and Elastic net regression) of a high-dimensional set of metabolites in order to discover host-associated biomarkers for identification of pathogens in community-acquired pneumonia (CAP) patients

## Teaching

During my PhD, I was also involved in teaching activities, which included supervising students for their research internships, working together with instructors to incorporate PKPD modelling into their course curriculum, as well as giving lectures.

Previous teaching experiences include:

-   BSc Pharmacokinetics & ADME course (2022, 2023)

-   MSc Pharmacokinetics & ADME course (2022, 2023)

## Education

-   PhD in Clinical Pharmacometrics \| Apr 2022 - 2026

    Department of Clinical Pharmacology and Pharmacy, Amsterdam UMC \| Amsterdam, the Netherlands

-   MSc in Bio-Pharmaceutical Sciences \| Sept 2019 - Mar 2022

    Quantitative Pharmacology & Pharmacy, LACDR, Leiden University \| Leiden, the Netherlands

-   BSc in Bio-Pharmaceutical Sciences \| Sept 2016 - Jul 2019

    Quantitative Pharmacology & Pharmacy, LACDR, Leiden University \| Leiden, the Netherlands
